---
elasticsearch:
  hosts:
    el-instance:
      ansible_host: 84.252.142.248
kibana:
  hosts:
    k-instance:
      ansible_host: 84.252.138.176
app:
  hosts:
    app-instance:
      ansible_host: 84.252.137.21
