---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.1.4"
    name: elastic
  - src: git@github.com:yuggoth/kibana-role.git
    scm: git
    version: "1.0.0"
    name: kibana
  - src: git@github.com:yuggoth/filebeat-role.git
    scm: git
    version: "1.0.0"
    name: filebeat

